spring:
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_BONSAI_URI}
      username: ${ELASTICSEARCH_BONSAI_USERNAME}
      password: ${ELASTICSEARCH_BONSAI_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: chatty
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS}
  oauth2:
    authorizedRedirectUris: ${AUTHORIZED_REDIRECT_URIS}
  google:
    drive:
      parent: ${GOOGLE_DRIVE_PARENT}