spring:
  datasource:
    url: jdbc:postgresql://ec2-3-222-74-92.compute-1.amazonaws.com:5432/darevrb4nvlt5i
    username: hxzlwnyyapyglk
    password: d57077edeb453adb784a70568a9b541ab0b43ae7809a6de7c67fdfc6bc8bb599
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  elasticsearch:
    rest:
      uris: ${ELASTICSEARCH_BONSAI_URI}
      username: ${ELASTICSEARCH_BONSAI_USERNAME}
      password: ${ELASTICSEARCH_BONSAI_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: chatty
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS}
  oauth2:
    authorizedRedirectUris: ${AUTHORIZED_REDIRECT_URIS}
  google:
    drive:
      parent: ${GOOGLE_DRIVE_PARENT}